version: '3'

services:
  mysql:
    container_name: laravelpress_mysql
    build:
      context: app/mysql
      args:
        - MYCONF=my.cnf
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: laravelpress
      MYSQL_PASSWORD: laravelpress
      MYSQL_DATABASE: laravelpress
    ports:
      - 33069:3306

  nginx:
    container_name: laravelpress_nginx
    image: nginx:stable-alpine
    volumes:
       - ./app/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
       - ./data/app:/app
    links:
      - app
    depends_on:
      - app
    ports:
      - 30089:80

  app:
    container_name: laravelpress_app
    build:
        context: ../
        dockerfile: docker/app/Dockerfile
    volumes:
        - ./app/php/custom.php.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./data/app:/app
    expose:
      - 9000
    depends_on:
      - mysql
      - redis

  redis:
    container_name: laravelpress_redis
    image: redis:5.0.7-alpine


